# Generated by Django 2.1.3 on 2018-11-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_type',
            new_name='roles',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introduction',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
