# Generated by Django 2.1.3 on 2018-11-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_casemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseModel',
            new_name='CaseInfo',
        ),
    ]
