# Generated by Django 2.1.3 on 2018-11-30 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181130_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseinfo',
            name='case_id',
            field=models.IntegerField(),
        ),
    ]
