# Generated by Django 2.1.3 on 2018-11-30 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181130_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
