# Generated by Django 2.1.3 on 2018-11-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181130_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
