# Generated by Django 2.1.3 on 2018-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181130_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='introduction',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
