# Generated by Django 2.1.3 on 2018-12-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181220_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Modules',
        ),
    ]
