# Generated by Django 2.1.3 on 2018-12-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181220_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.Projects'),
        ),
    ]
